// @ts-nocheck -- skip type checking
import * as docs_0 from "../content/docs/index.mdx?collection=docs&hash=1784003752052"
import * as conditions_15 from "../content/conditions/wrist-pain.mdx?collection=conditions&hash=1784003752052"
import * as conditions_14 from "../content/conditions/sports-injury.mdx?collection=conditions&hash=1784003752052"
import * as conditions_13 from "../content/conditions/shoulder-pain.mdx?collection=conditions&hash=1784003752052"
import * as conditions_12 from "../content/conditions/sciatica.mdx?collection=conditions&hash=1784003752052"
import * as conditions_11 from "../content/conditions/osteoarthritis.mdx?collection=conditions&hash=1784003752052"
import * as conditions_10 from "../content/conditions/neck-pain.mdx?collection=conditions&hash=1784003752052"
import * as conditions_9 from "../content/conditions/muscle-weakness.mdx?collection=conditions&hash=1784003752052"
import * as conditions_8 from "../content/conditions/knee-pain.mdx?collection=conditions&hash=1784003752052"
import * as conditions_7 from "../content/conditions/joint-pain.mdx?collection=conditions&hash=1784003752052"
import * as conditions_6 from "../content/conditions/index.mdx?collection=conditions&hash=1784003752052"
import * as conditions_5 from "../content/conditions/hip-pain.mdx?collection=conditions&hash=1784003752052"
import * as conditions_4 from "../content/conditions/frozen-shoulder.mdx?collection=conditions&hash=1784003752052"
import * as conditions_3 from "../content/conditions/fibromyalgia.mdx?collection=conditions&hash=1784003752052"
import * as conditions_2 from "../content/conditions/elbow-pain.mdx?collection=conditions&hash=1784003752052"
import * as conditions_1 from "../content/conditions/back-pain.mdx?collection=conditions&hash=1784003752052"
import * as conditions_0 from "../content/conditions/arthritis.mdx?collection=conditions&hash=1784003752052"
import * as biomarkers_14 from "../content/biomarkers/vitamin-d.mdx?collection=biomarkers&hash=1784003752052"
import * as biomarkers_13 from "../content/biomarkers/vegf.mdx?collection=biomarkers&hash=1784003752052"
import * as biomarkers_12 from "../content/biomarkers/pinp.mdx?collection=biomarkers&hash=1784003752052"
import * as biomarkers_11 from "../content/biomarkers/parathyroid-hormone.mdx?collection=biomarkers&hash=1784003752052"
import * as biomarkers_10 from "../content/biomarkers/osteocalcin.mdx?collection=biomarkers&hash=1784003752052"
import * as biomarkers_9 from "../content/biomarkers/mmp-9.mdx?collection=biomarkers&hash=1784003752052"
import * as biomarkers_8 from "../content/biomarkers/mda.mdx?collection=biomarkers&hash=1784003752052"
import * as biomarkers_7 from "../content/biomarkers/index.mdx?collection=biomarkers&hash=1784003752052"
import * as biomarkers_6 from "../content/biomarkers/il-6.mdx?collection=biomarkers&hash=1784003752052"
import * as biomarkers_5 from "../content/biomarkers/ctx-ii.mdx?collection=biomarkers&hash=1784003752052"
import * as biomarkers_4 from "../content/biomarkers/crp.mdx?collection=biomarkers&hash=1784003752052"
import * as biomarkers_3 from "../content/biomarkers/ck-mm.mdx?collection=biomarkers&hash=1784003752052"
import * as biomarkers_2 from "../content/biomarkers/calcium-phosphorus-ratio.mdx?collection=biomarkers&hash=1784003752052"
import * as biomarkers_1 from "../content/biomarkers/bdnf.mdx?collection=biomarkers&hash=1784003752052"
import * as biomarkers_0 from "../content/biomarkers/aldolase-a.mdx?collection=biomarkers&hash=1784003752052"
import { _runtime } from "fumadocs-mdx/runtime/next"
import * as _source from "../source.config"
export const biomarkers = _runtime.docs<typeof _source.biomarkers>([{ info: {"path":"aldolase-a.mdx","fullPath":"content/biomarkers/aldolase-a.mdx"}, data: biomarkers_0 }, { info: {"path":"bdnf.mdx","fullPath":"content/biomarkers/bdnf.mdx"}, data: biomarkers_1 }, { info: {"path":"calcium-phosphorus-ratio.mdx","fullPath":"content/biomarkers/calcium-phosphorus-ratio.mdx"}, data: biomarkers_2 }, { info: {"path":"ck-mm.mdx","fullPath":"content/biomarkers/ck-mm.mdx"}, data: biomarkers_3 }, { info: {"path":"crp.mdx","fullPath":"content/biomarkers/crp.mdx"}, data: biomarkers_4 }, { info: {"path":"ctx-ii.mdx","fullPath":"content/biomarkers/ctx-ii.mdx"}, data: biomarkers_5 }, { info: {"path":"il-6.mdx","fullPath":"content/biomarkers/il-6.mdx"}, data: biomarkers_6 }, { info: {"path":"index.mdx","fullPath":"content/biomarkers/index.mdx"}, data: biomarkers_7 }, { info: {"path":"mda.mdx","fullPath":"content/biomarkers/mda.mdx"}, data: biomarkers_8 }, { info: {"path":"mmp-9.mdx","fullPath":"content/biomarkers/mmp-9.mdx"}, data: biomarkers_9 }, { info: {"path":"osteocalcin.mdx","fullPath":"content/biomarkers/osteocalcin.mdx"}, data: biomarkers_10 }, { info: {"path":"parathyroid-hormone.mdx","fullPath":"content/biomarkers/parathyroid-hormone.mdx"}, data: biomarkers_11 }, { info: {"path":"pinp.mdx","fullPath":"content/biomarkers/pinp.mdx"}, data: biomarkers_12 }, { info: {"path":"vegf.mdx","fullPath":"content/biomarkers/vegf.mdx"}, data: biomarkers_13 }, { info: {"path":"vitamin-d.mdx","fullPath":"content/biomarkers/vitamin-d.mdx"}, data: biomarkers_14 }], [])
export const blog = _runtime.docs<typeof _source.blog>([], [])
export const conditions = _runtime.docs<typeof _source.conditions>([{ info: {"path":"arthritis.mdx","fullPath":"content/conditions/arthritis.mdx"}, data: conditions_0 }, { info: {"path":"back-pain.mdx","fullPath":"content/conditions/back-pain.mdx"}, data: conditions_1 }, { info: {"path":"elbow-pain.mdx","fullPath":"content/conditions/elbow-pain.mdx"}, data: conditions_2 }, { info: {"path":"fibromyalgia.mdx","fullPath":"content/conditions/fibromyalgia.mdx"}, data: conditions_3 }, { info: {"path":"frozen-shoulder.mdx","fullPath":"content/conditions/frozen-shoulder.mdx"}, data: conditions_4 }, { info: {"path":"hip-pain.mdx","fullPath":"content/conditions/hip-pain.mdx"}, data: conditions_5 }, { info: {"path":"index.mdx","fullPath":"content/conditions/index.mdx"}, data: conditions_6 }, { info: {"path":"joint-pain.mdx","fullPath":"content/conditions/joint-pain.mdx"}, data: conditions_7 }, { info: {"path":"knee-pain.mdx","fullPath":"content/conditions/knee-pain.mdx"}, data: conditions_8 }, { info: {"path":"muscle-weakness.mdx","fullPath":"content/conditions/muscle-weakness.mdx"}, data: conditions_9 }, { info: {"path":"neck-pain.mdx","fullPath":"content/conditions/neck-pain.mdx"}, data: conditions_10 }, { info: {"path":"osteoarthritis.mdx","fullPath":"content/conditions/osteoarthritis.mdx"}, data: conditions_11 }, { info: {"path":"sciatica.mdx","fullPath":"content/conditions/sciatica.mdx"}, data: conditions_12 }, { info: {"path":"shoulder-pain.mdx","fullPath":"content/conditions/shoulder-pain.mdx"}, data: conditions_13 }, { info: {"path":"sports-injury.mdx","fullPath":"content/conditions/sports-injury.mdx"}, data: conditions_14 }, { info: {"path":"wrist-pain.mdx","fullPath":"content/conditions/wrist-pain.mdx"}, data: conditions_15 }], [])
export const docs = _runtime.docs<typeof _source.docs>([{ info: {"path":"index.mdx","fullPath":"content/docs/index.mdx"}, data: docs_0 }], [])
export const showcase = _runtime.docs<typeof _source.showcase>([], [])